import argparse
import os

import github


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('repo', type=str)
    parser.add_argument('branch', type=str)
    parser.add_argument('title', type=str)
    args = parser.parse_args()

    g = github.Github('sergeant-wizard', os.environ['GITHUB_ACCESS_TOKEN'])
    repo = g.get_repo(args.repo)
    pr = repo.create_pull(
        title=args.title, base='master', head=args.branch,
        body='PR generated by auto_merge',
    )
    pr.merge()


if __name__ == '__main__':
    main()
